# Fabric 26.2 Create addon (Create Fly)
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.11
fabric_version=0.152.1+26.2

emf_version=3.3.2
etf_version=7.2.1
create_fly_version=26.2-rc-2-6.0.9-1

mod_id=emf_compat_create
mod_name=EMF Compat: Create
mod_description=Integrates Create with EMF. Suppresses conflicting player animations during skyhook, grappling hooks and other Create-specific poses.
mod_version=2.0.0
