modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="emf_compat_corpse.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile = "icon.png"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="emf_compat_core"
type="required"
versionRange="[1.0.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="corpse"
type="required"
versionRange="[1.0.14,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="entity_model_features"
type="required"
versionRange="[3.2.4,)"
ordering="AFTER"
side="CLIENT"
