plugins {
    id 'java'
    id 'net.fabricmc.fabric-loom' version '1.17.11'
}

version = '1.0.0'
base { archivesName = 'mctest_driver-fabric-26.3' }
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

dependencies {
    minecraft "com.mojang:minecraft:26.3"
    implementation "net.fabricmc:fabric-loader:0.19.5"
    implementation "net.fabricmc.fabric-api:fabric-api:0.162.0+26.3"
}

tasks.withType(JavaCompile).configureEach { it.options.release = 25 }
