plugins {
    id 'java'
    id 'net.fabricmc.fabric-loom-remap' version '1.17.11'
}

version = '1.0.0'
base { archivesName = 'mctest_driver-fabric-1.21.1' }
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

dependencies {
    minecraft "com.mojang:minecraft:1.21.1"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:0.16.14"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.116.17+1.21.1"
}

tasks.withType(JavaCompile).configureEach { it.options.release = 21 }
